/*  Muhammad Mahad 21L-6195
Design a synchronous multi-threaded application for the following tasks to be executed
in an order.
Write a program which takes some positive integer (let’s say N) as command
line argument
It creates a thread, and send N to it as parameter.
This thread is a fibonacciGenerator. The function returns the generated
Fibonacci series until N to the main thread, which prints in on the screen along
with the thread ID.
This series is to be passed to another thread by the main thread.
This new worker has to count the number of even numbers and return the
count to main thread, which prints it along with the 2nd thread’s id.
Then the series is to be passed to a third thread by the main thread.
This new worker has to count the number of odd numbers and return the
count to main thread, which prints it along with the 3rd thread’s id.
Finally the sum of this series is calculated by a fourth thread and written to a
file named sum.txt. This thread also returns the sum value to the main thread
where it is printed along with the thread ID.
Also, create a suitable MAKEFILE for the execution of this program.
*/
#include <stdio.h>    // printf
#include <pthread.h>  // pthread_create, pthread_exit
#include <unistd.h>   // sleep
#include <stdlib.h>   // exit
#include <stdint.h>   // intptr_t
#include <string.h>   // strlen
#include <fcntl.h>    // open
#include <sys/stat.h> // open
#include <sys/types.h>// open
#include <unistd.h>   // write, close

int LIMIT = 0;

void *fib_sequence(void *arg){
    int n = (intptr_t)arg;
    // printf("%d",n);
    // creating dynamic array for fib sequence
    int *fib = (int *)malloc(n * sizeof(int));
    fib[0] = 0;
    fib[1] = 1;
    for (int i = 2; i < n; i++)
    {
        fib[i] = fib[i - 1] + fib[i - 2];
    }

    // printing fib sequence
    // for (int i = 0; i < n; i++)
    // {
    //     printf("%d ", fib[i]);
    // }
    // returning fib sequence
    pthread_exit(fib);
}

void *even_count(void *arg){
    int *fib = (int *)arg;
    int count = 0;
    for (int i = 0; i < LIMIT /*fib[i] <= LIMIT*/; i++)
    {
        if (fib[i] % 2 == 0)
        {
            count++;
        }
    }
    // returning count of even numbers
    pthread_exit((void *)(intptr_t)count);
}

void *odd_count(void *arg){
    int *fib = (int *)arg;
    int count = 0;
    for (int i = 0; i < LIMIT /*fib[i] <= LIMIT*/; i++)
    {
        if (fib[i] % 2 != 0)
        {
            count++;
        }
    }
    // returning count of odd numbers
    pthread_exit((void *)(intptr_t)count);
}

void *sum(void *arg){
    int *fib = (int *)arg;
    int sum = 0;
    for (int i = 0; i < LIMIT /*fib[i] <= LIMIT*/; i++)
    {
        sum += fib[i];
    }
    // writing sum to file
    int fd = open("sum.txt", O_WRONLY | O_CREAT, 0644);
    char buffer[100];
    sprintf(buffer, "%d", sum);
    write(fd, buffer, strlen(buffer));
    close(fd);
    // returning sum
    pthread_exit((void *)(intptr_t)sum);
}

int main(int argc, char *argv[]){
    // checking for command line arguments
    int N = atoi(argv[1]);
    LIMIT = N;
    if (argc != 2)
    {
        printf("Usage: %s <positive integer>\n", argv[0]);
        exit(1);
    }
    // creating threads
    pthread_t fib_thread, even_thread, odd_thread, sum_thread;
    // creating fibonacci sequence
    pthread_create(&fib_thread, NULL, fib_sequence, (void *)(intptr_t)atoi(argv[1]));

    // waiting for fibonacci sequence to be generated
    int *fib;
    pthread_join(fib_thread, (void **)&fib);
    // printing fibonacci sequence
    printf("Fibonacci sequence generated by thread %lu: ", fib_thread);
    printf("%d ", fib[0]);
    for (int i = 0; i < LIMIT /*fib[i] <= LIMIT*/; i++)
    {
        printf("%d ", fib[i]);
    }
    printf("\n");

    // counting even numbers
    pthread_create(&even_thread, NULL, even_count, (void *)fib);
    // waiting for even numbers to be counted
    int even;
    pthread_join(even_thread, (void **)&even);
    // printing even numbers
    printf("Even numbers counted by thread %lu: %d\n", even_thread, even - 1);

    // counting odd numbers
    pthread_create(&odd_thread, NULL, odd_count, (void *)fib);
    // waiting for odd numbers to be counted
    int odd;

    pthread_join(odd_thread, (void **)&odd);
    // printing odd numbers
    printf("Odd numbers counted by thread %lu: %d\n", odd_thread, odd);

    // calculating sum
    pthread_create(&sum_thread, NULL, sum, (void *)fib);
    // waiting for sum to be calculated
    int sum;
    pthread_join(sum_thread, (void **)&sum);
    // printing sum
    printf("Sum calculated by thread %lu: %d\n", sum_thread, sum);

    // deallocating
    free(fib);

    return 0;
}