# Compiling q2/Makefile

CC = g++
CFLAGS = -Wall -g 
LDFLAGS = -lm

q2.out : q2.cpp
	$(CC) $^ -o $@ $(CFLAGS)

clean: 
	rm -f *.out

# Write "1 2 3 4" in text file and save it as "input.txt"

file:
	echo "1 2 3 4" > input.txt
